//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abroad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int AdID { get; set; }
        public string ImageURL { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string StatusAd { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
