//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abroad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultationAppointment
    {
        public int AppointmentID { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public string NumberphoneCon { get; set; }
        public Nullable<int> ConsultantID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public System.DateTime DateAndTime { get; set; }
        public string StatusCon { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
