//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abroad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int ProfileID { get; set; }
        public string ImgPro { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string PhoneNumber { get; set; }
        public string AddressP { get; set; }
        public string EmailP { get; set; }
        public string EducationLevel { get; set; }
        public string Major { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public string TrangThai { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual University University { get; set; }
    }
}
